[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log

[program:llama-server]
command=llama-server -m %(ENV_MODEL_PATH)s -c %(ENV_LLM_CONTEXT)s -ngl %(ENV_LLM_NGL)s -t %(ENV_LLM_THREADS)s --port 8080 --host 127.0.0.1 --log-disable
autostart=true
autorestart=true
stdout_logfile=/var/log/llama.log
stderr_logfile=/var/log/llama.err

[program:ml-worker]
command=python3 /app/ml-worker/server.py
environment=ML_WORKER_PORT="%(ENV_ML_WORKER_PORT)s",LLM_PORT="8080",GPU_TYPE="%(ENV_BUILD_TYPE)s"
autostart=true
autorestart=true
stdout_logfile=/var/log/ml-worker.log
stderr_logfile=/var/log/ml-worker.err

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/nginx-access.log
stderr_logfile=/var/log/nginx-error.log
